# Generated by Django 5.2.11 on 2026-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('posicio', models.CharField(max_length=100)),
                ('nacionalitat', models.CharField(max_length=100)),
                ('titols', models.TextField()),
            ],
        ),
    ]
