# Generated by Django 5.2.11 on 2026-02-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('any', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='titols',
        ),
        migrations.AddField(
            model_name='jugador',
            name='titols',
            field=models.ManyToManyField(related_name='jugadors', to='jugadors.titol'),
        ),
    ]
